name: Markdown Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Run markdownlint
        run: markdownlint **/*.md
